In [2]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv("project datas/Phase 1/Linear Regression/train.csv")
df

id  MonsoonIntensity  TopographyDrainage  RiverManagement  \
0              0                 5                   8                5   
1              1                 6                   7                4   
2              2                 6                   5                6   
3              3                 3                   4                6   
4              4                 5                   3                2   
...          ...               ...                 ...              ...   
1048570  1048570                 6                   6                5   
1048571  1048571                 5                   4                4   
1048572  1048572                 3                   5                5   
1048573  1048573                 4                   4                2   
1048574  1048574                 5                   3                4   

         Deforestation  Urbanization  ClimateChange  DamsQuality  Siltation  \
0                    8             6              4            4          3   
1                    4             8              8            3          5   
2                    7             3              7            1          5   
3                    5             4              8            4          7   
4                    6             4              4            3          3   
...                ...           ...            ...          ...        ...   
1048570              3             5              3            7          4   
1048571              5             5              4            5          3   
1048572              9             5              6            1          4   
1048573              3             4              7           11          3   
1048574              5             3              2            8         10   

         AgriculturalPractices  ...  DrainageSystems  CoastalVulnerability  \
0                            3  ...                5                     3   
1                            4  ...                7                     2   
2                            4  ...                7                     3   
3                            6  ...                2                     4   
4                            3  ...                2                     2   
...                        ...  ...              ...                   ...   
1048570                      4  ...                3                     6   
1048571                      6  ...                3                     4   
1048572                      5  ...                8                     5   
1048573                      3  ...                6                     3   
1048574                      5  ...                5                     6   

         Landslides  Watersheds  DeterioratingInfrastructure  PopulationScore  \
0                 3           5                            4                7   
1                 0           3                            5                3   
2                 7           5                            6                8   
3                 7           4                            4                6   
4                 6           6                            4                1   
...             ...         ...                          ...              ...   
1048570           8           5                            4                6   
1048571           6           3                            3                4   
1048572           3           5                            3                6   
1048573           7           1                            5                7   
1048574           4           7                            5                6   

         WetlandLoss  InadequatePlanning  PoliticalFactors  FloodProbability  
0                  5                   7                 3             0.445  
1                  3                   4                 3             0.450  
2                

In [16]:
for column in df.columns:
    mean_value = np.nanmean(df[column])  
    df[column].fillna(mean_value, inplace=True)

0

In [21]:
(df == 0).sum()


id                                    1
MonsoonIntensity                   5095
TopographyDrainage                 5179
RiverManagement                    5056
Deforestation                      5018
Urbanization                       5009
ClimateChange                      5025
DamsQuality                        5505
Siltation                          5071
AgriculturalPractices              5359
Encroachments                      5194
IneffectiveDisasterPreparedness    5057
DrainageSystems                    5245
CoastalVulnerability               5382
Landslides                         5197
Watersheds                         5057
DeterioratingInfrastructure        4650
PopulationScore                    5206
WetlandLoss                        4880
InadequatePlanning                 5269
PoliticalFactors                   5588
FloodProbability                      0
dtype: int64

In [22]:
(df == 0).sum(axis=1)

0          1
1          1
2          0
3          0
4          0
          ..
1048570    0
1048571    0
1048572    0
1048573    0
1048574    0
Length: 1048575, dtype: int64

In [49]:
y = df['FloodProbability'].to_numpy()
x = df.drop(['id', 'FloodProbability'], axis=1).to_numpy()

In [38]:
x.shape

(1048575, 20)

In [28]:
y

array([0.445, 0.45 , 0.53 , ..., 0.5  , 0.45 , 0.535])

In [32]:
y[2]

0.53

In [62]:
weights = np.full(20, 3, dtype=np.float64)
bias = 1
weights

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3.])

In [63]:
def linear_regression(alpha, bias, w, x, y):
    rows, columns = x.shape
    for i in range(rows):
        selected_row = x[i,:]
        predict = np.dot(selected_row, w) + bias
        real = y[i]
        for j in range(columns):
            w[j] -= selected_row[j] * (predict - real) * 2 * alpha
        bias -= (predict - real) * 2 * alpha
    return (w, bias)
    
    
    

In [64]:
w, b = linear_regression(0.00000001, bias, weights, x, y)
w, b

(array([ 1.14463351e-02,  4.23016130e-03, -9.08563984e-03,  1.34884100e-05,
         1.11651623e-04,  7.30355165e-03, -5.64599310e-03,  6.99616420e-03,
        -2.17790681e-03, -3.89283102e-03, -4.98907265e-03, -3.27464173e-03,
        -6.84600804e-03,  8.08899736e-03,  1.01504568e-02,  9.19842263e-03,
         8.87579190e-03, -4.05820582e-03, -3.39705776e-03,  1.57176564e-03]),
 0.39705519882586565)

In [45]:
w

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
b

array([0.50489133, 0.50489133, 0.50489133, 0.50489133, 0.50489133,
       0.50489133, 0.50489133, 0.50489133, 0.50489133, 0.50489133,
       0.50489133, 0.50489133, 0.50489133, 0.50489133, 0.50489133,
       0.50489133, 0.50489133, 0.50489133, 0.50489133, 0.50489133])